from crewai.flow import Flow, start, listen
from mars_exploration_flow.crews.mission_crew.mission_crew import MissionCrew
from mars_exploration_flow.crews.rover_crew.rover_crew import RoverCrew
from mars_exploration_flow.crews.drone_crew.drone_crew import DroneCrew
from mars_exploration_flow.crews.integration_crew.integration_crew import (
    IntegrationCrew,
)
from mars_exploration_flow.tools.mission_files_helper import MissionFiles
from mars_exploration_flow.types import MissionState


class MarsMissionFlow(Flow[MissionState]):
    """
    CrewAI Flow coordinating the Mars exploration mission.
    Execution order (sequential):
        1. Mission Crew
        2. Rover Crew and Drone Crew (in parallel)
        3. Integration Crew
    """

    # Change to True to load from saved files
    initial_state = MissionState(load_from_files=False)

    @start()
    def run_mission_crew(self):
        """
        Runs the Mission Crew workflow using a mission report as input
        and produces a structured mission analysis for the next pipeline step

        Inputs:
            - mission_report (str):
                Markdown content loaded from `mission_report.md` (example).

        Outputs:
            - MissionAnalysisOutput:
                Generated mission analysis stored in `self.state.mission_analysis`
                and persisted to `mission_analysis.md`.
        """

        print("*** LAUNCH MISSION CREW ***")
        output = (
            MissionCrew()
            .crew()
            .kickoff(inputs={"mission_report": MissionFiles.get_mission_report()})
        )

        self.state.mission_analysis = output.tasks_output[0]
        MissionFiles.set_mission_analysis(self.state.mission_analysis)
        return "Mission analysis completed"

    @listen(run_mission_crew)
    def run_rover_crew(self, _):
        """
        Executes the Rover Crew to generate the rover execution plan.

        Inputs:
            - rovers (list):
                Rover definitions loaded from `rovers.json` (file).
            - mission_analysis (MissionAnalysisOutput-pydantic):
                Mission analysis generated by the Mission Crew or loaded from disk.

        Outputs:
            - RoverPlanOutput (pydantic):
                Generated rover plan used in subsequent workflow steps.
        """
        print("*** LAUNCH ROVER CREW ***")

        if self.state.load_from_files:
            self.state.mission_analysis = MissionFiles.get_mission_analysis()

        output = (
            RoverCrew()
            .crew()
            .kickoff(
                inputs={
                    "rovers": MissionFiles.get_rovers(),
                    "mission_analysis_file": self.state.mission_analysis.model_dump_json(),
                }
            )
        )

        # Update rover plan and save to file
        self.state.rover_plan = output.tasks_output[0]
        MissionFiles.set_rover_plan(self.state.rover_plan)

        return "Rover planning completed"

    @listen(run_mission_crew)
    def run_drone_crew(self, _):
        """
        Executes the Drone Crew to generate the drone execution plan.

        Inputs:
            - drones (list):
                Drone definitions loaded from `drones.json` (file).
            - mission_analysis (MissionAnalysisOutput-pydantic):
                Mission analysis generated by the Mission Crew or loaded from disk.

        Outputs:
            - DronePlanOutput (pydantic):
                Generated drone plan used in subsequent workflow steps.
        """
        print("*** LAUNCH DRONE CREW ***")

        if self.state.load_from_files:
            self.state.mission_analysis = MissionFiles.get_mission_analysis()

        output = (
            DroneCrew()
            .crew()
            .kickoff(
                inputs={
                    "drones": MissionFiles.get_drones(),
                    "mission_analysis_file": self.state.mission_analysis.model_dump_json(),
                }
            )
        )

        # Update drone plan and save to file
        self.state.drone_plan = output.tasks_output[0]
        MissionFiles.set_drone_plan(self.state.drone_plan)
        return "Drone planning completed"

    @listen(run_rover_crew)
    @listen(run_drone_crew)
    def run_integration_crew(self, _):
        """
        Executes the Integration Crew to generate the final mission report.
        Integrates mission analysis, rover plan, and drone plan into a
        consolidated Mars mission report.

        Inputs:
            - mission_analysis (MissionAnalysisOutput)
            - rover_plan (RoverPlanOutput)
            - drone_plan (DronePlanOutput)

        Outputs:
            - Final mission report:
                Integrated result printed to stdout and used as the final output
                of the mission workflow.
        """
        print("*** LAUNCH INTEGRATION CREW ***")

        if self.state.load_from_files:
            self.state.mission_analysis = MissionFiles.get_mission_analysis()
            self.state.rover_plan = MissionFiles.get_rover_plan()
            self.state.drone_plan = MissionFiles.get_drone_plan()

        output = (
            IntegrationCrew()
            .crew()
            .kickoff(
                inputs={
                    "mission_analysis": self.state.mission_analysis.model_dump_json(),
                    "rover_plan": (
                        self.state.rover_plan.model_dump_json()
                        if self.state.rover_plan
                        else {}
                    ),
                    "drone_plan": (
                        self.state.drone_plan.model_dump_json()
                        if self.state.drone_plan
                        else {}
                    ),
                }
            )
        )

        final_mission_report = output.tasks_output[0]

        # Update rover plan and save to file
        MissionFiles.set_final_mission_plan(final_mission_report)

        print("**** FINAL REPORT ****:\n", final_mission_report.raw)
        return "Mars mission report completed"
